### ISSUE TITLE
No module named 'discord'

### ISSUE THREAD

**Issue by DrizzExotic** [SSIDSpin/Minecraft-Account-Discord-Bot-Phisher#2]
C:\Users\Drizz\Desktop\blackmonkey>python bot.py
Traceback (most recent call last):
  File "C:\Users\Drizz\Desktop\blackmonkey\bot.py", line 5, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'

C:\Users\marle\Desktop\Minecraft-Account-Discord-Bot-Phisher>

**Comment by screened** [comment]
dumb retard
