### ISSUE TITLE
Bot not online 24/7

### ISSUE THREAD

**Issue by dyondd2** [SSIDSpin/Minecraft-Account-Discord-Bot-Phisher#3]
so the problem i am occurring is  the bot  is online for a  little time and goes offline  and  i have tried many website to make it 24/7 online but  if it works  then the properties of the bot chnages and its not able to do its work please tell the fix ASAP,
thank you

**Comment by SSIDSpin** [comment]
Wanna ping me on discord as depending on what site you used to host it, as some run using node js for example.

**Comment by dyondd2** [comment]
SSIDSpin  if you have any more  pshior bot or anything like that for minecraft  please tell me and i also need  your help  in a project if  you can  please tell me 
thank you

**Comment by SSIDSpin** [comment]
Wanna send me a message on discord,
It's like on my git :)

**Comment by SSIDSpin** [comment]
Wanna shoot me a dm on discord, spinontop

**Comment by dyondd2** [comment]
my id is  the_chill_guy_

**Comment by dyondd2** [comment]
i have sent you  the req

**Comment by dyondd2** [comment]
if you know  the   NachtAuth2-main project , im trying it but its too hard for  me cuz i dont have expertise in these type of thing and i think  its pretty easy for you to help me in NachtAuth2-main or if you have any more pishor bots  like this  and it also  might help

**Comment by DanGILC-137** [comment]
hi when doing !webhook "mywebhook" it says on the console
ERROR | 2024-07-16 17:53:42,788 | discord.ext.commands.bot | Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "webhook" is not found
i have typed !sync global
