### ISSUE TITLE
Commands error

### ISSUE THREAD

**Issue by DanGILC-137** [SSIDSpin/Minecraft-Account-Discord-Bot-Phisher#4]
hi when doing !webhook "mywebhook" it says on the console
ERROR | 2024-07-16 17:53:42,788 | discord.ext.commands.bot | Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "webhook" is not found
i have typed !sync global

**Comment by SSIDSpin** [comment]
It's / commands :)

**Comment by DanGILC-137** [comment]
yeah but they dont work
