### ISSUE TITLE
Verify Role

### ISSUE THREAD

**Issue by Ayhancann** [SSIDSpin/Minecraft-Account-Discord-Bot-Phisher#7]
if u click  verify message and write ur minecraft name and gmail u get a role add this

**Comment by SSIDSpin** [comment]
Kinda a good idea, however roles work off a ID so for example the role 'Verified' for example will have a different ID in every server. So it makes it difficult for users who don't understand code well.

**Comment by Ayhancann** [comment]
I made it but idk it works properly and ppl dont understand ur code wont install some random things

**Comment by SSIDSpin** [comment]
Shoot me a dm on discord I can take a look if it will work or not.

**Comment by Ayhancann** [comment]
In my county its midnight iwill send u tmrw and whats ur discord?

**Comment by SSIDSpin** [comment]
My discord is Spinontop
